### ISSUE TITLE
Lombardy dataset

### ISSUE THREAD

**Issue by chiaraunipg** [TNO/Covid-SEIR#1]
Is it possible to see the dataset used for calibration of Lombardy region?
Thank you.

**Comment by weesjdamv** [comment]
Hi Chiara,

Yes off course (I will put it on github soon We will  also include an update for the software with nicer output tomorrow most likely).

Please note in the input file the hospitalization data is in column cumulative. It should be actually in the column actual (last), but it will be overwritten if you do so (accidently)

In the new version that will be ok


Kind regards,
Jan-Diederik


[cid:image001.png@01D60D24.36C1C2A0]

**Comment by chiaraunipg** [comment]
Ok perfect I will take a look at it and at the new version of the algorithm! Thank you very much!

Best regards,
Chiara
